### ISSUE TITLE
it breaks the last UTF-8 character in a very long message and the UTF-8 invalid character displayed as ? in weechat 0.4.0

### ISSUE THREAD

**Issue by wind0204** [changwoo/irc-relay#3]
it breaks the last UTF-8 character in a very long message, so the UTF-8 invalid character will be displayed as '?' in weechat 0.4.0. XChat user might see it with no problem.

to reproduce this problem, speak the following message when your nickname is longer than 5 bytes or 5 bytes long and you are using an irc client that is not weechat

```
조기숙 교수를 필두로 한 어떤 이들은 “참여정부는 심판당한 적이 없으며 2007년 대선은 정동영의 패배였다”, “노무현을 내세운 선거는 언제나 승리했고 그렇지 못한 선거는 패배했다”, “문재인 후보의 ‘좌클릭’이 패배를 낳았다”는 식의 거의 대체역사소설이나 평행우주에서나 가능할 법 같은 가설을 통계나 과학의 이름으로 주장하기
```

**Comment by changwoo** [comment]
Hello,

Currently there's no plan to improve this program anymore.

Feel free to fork and add your code.
