### ISSUE TITLE
password support?

### ISSUE THREAD

**Issue by doged** [changwoo/irc-relay#4]
would also like to add password feature, for cloaking purpose. should be simple.

also, for standard english encoding, both would be utf-8 correct?

**Comment by doged** [comment]
@mrsmn is this what you meant? i am working on it now, ill submit a pull request later if i get it working

**Comment by barnumbirr** [comment]
@doged What I meant was NickServ password support so you can identify to the service.

**Comment by changwoo** [comment]
Hello,

Currently there's no plan to improve this program anymore.

Feel free to fork and add your code.
